services:
  go_db:
    container_name: "go_db"
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - .env
    networks:
      - "go_network"

  go_pgadmin:
    container_name: "go_pgadmin"
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      - go_db
    restart: always
    env_file:
      - .env
    networks:
      - "go_network"

networks:
  go_network:
    driver: bridge

volumes: 
  postgres_data: